add_requires("glad", "glfw", "glm", "stb", "unordered_dense", "nlohmann_json")
set_languages("c++20")

target("imgui")
  set_kind("static")
  add_files("lib/imgui/*.cpp")
  add_includedirs("include/imgui")
  add_packages("glad", "glfw", "glm")

target("stb")
  set_kind("static")
  add_files("lib/stb/*.cpp")
  add_packages("stb")

target("voxel")
  set_kind("binary")
  add_files("src/*.cpp")
  add_includedirs("include", "shaders")
  add_packages("glad", "glfw", "glm", "stb", "unordered_dense", "nlohmann_json")
  add_cflags("-g", "-O1", "-Wall", "-flto")
  add_linkdirs("lib")
  add_syslinks("glfw", "GLU", "GL", "dl", "pthread")
  add_rpathdirs("~/.local/lib")
  add_links("FastNoise")
  add_deps("imgui", "stb")
